### ISSUE TITLE
Errors when following Husky UR5 Mobile Manipulation Demo (Simulation)

### ISSUE THREAD

**Issue by stevensu1838** [husky/husky_manipulation#5]
Hi,
Ubuntu 14.04 ROS indigo  It is in Simulation
I am following your great tutorial on  [Husky UR5 Mobile Manipulation Demo (Simulation)](https://www.clearpathrobotics.com/assets/guides/husky/HuskyManip.html)
1.sudo apt-get install ros-indigo-husky-simulator && sudo apt-get install ros-indigo-husky-ur5-moveit-config
2.mkdir -p devel_ws/src && cd devel_ws/src && catkin_init_workspace
3.git clone https://github.com/ros-industrial/universal_robot && cd ..
4.catkin_make install
Before running each command in this tutorial, run this command or add it to your ~/.bashrc file:
5.source ~/devel_ws/devel/setup.bash

However, when I was trying to Bring up Gazebo And The Husky with the following command:
Running the launch file which will bring up Gazebo with the Husky + UR5.

6.roslaunch husky_gazebo husky_playpen.launch ur5_enabled:=true

It throws errors as below. Can you please help?
```
ted@vra1:~/devel_ws$ roslaunch husky_gazebo husky_playpen.launch ur5_enabled:=true
... logging to /home/ted/.ros/log/52c54970-156e-11ea-b2c3-4c72b923f66b/roslaunch-vra1-13491.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Traceback (most recent call last):
  File "/opt/ros/indigo/share/xacro/xacro.py", line 62, in <module>
    xacro.main()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 696, in main
    eval_self_contained(doc)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 626, in eval_self_contained
    eval_all(doc.documentElement, macros, symbols)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 553, in eval_all
    eval_all(body, macros, scoped)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 553, in eval_all
    eval_all(body, macros, scoped)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 497, in eval_all
    result = eval_text(at[1], symbols)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 483, in eval_text
    results.append(handle_expr(lex.next()[1][2:-1]))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 470, in handle_expr
    return eval_expr(lex, symbols)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 444, in eval_expr
    result = eval_term(lex, symbols)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 418, in eval_term
    result = eval_factor(lex, symbols)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 398, in eval_factor
    return neg * eval_lit(lex, symbols)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 369, in eval_lit
    raise XacroException("Property wasn't defined: %s" % str(ex))
xacro.XacroException: Property wasn't defined: u'pi'
while processing /opt/ros/indigo/share/husky_gazebo/launch/husky_empty_world.launch:
while processing /opt/ros/indigo/share/husky_gazebo/launch/spawn_husky.launch:
Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/indigo/share/xacro/xacro.py '/opt/ros/indigo/share/husky_gazebo/urdf/description.gazebo.xacro'     laser_enabled:=true     ur5_enabled:=true     kinect_enabled:=false     ] returned with code [1]. 

Param xml is <param command="$(find xacro)/xacro.py '$(arg husky_gazebo_description)'     laser_enabled:=$(arg laser_enabled)     ur5_enabled:=$(arg ur5_enabled)     kinect_enabled:=$(arg kinect_enabled)     " name="robot_description"/>
The traceback for the exception was written to the log file
ted@vra1:~/devel_ws$ 

```

**Comment by dniewinski** [comment]
Hi @stevensu1838.  That tutorial is using a deprecated repository (DualUR5Husky, not this one) which is no longer supported.  Please update to Kinetic or Melodic as the simulation support is better.
